version: '3'

services:
  spark:
    image: bitnami/spark:3.3.1
    environment:
      - SPARK_MODE=master
    ports:
      - '8080:8080'
      - '7077:7077'
    volumes:
      - $PWD:/home/jovyan/work
  spark-worker:
    image: bitnami/spark:3.3.1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_EXECUTOR_MEMORY=4G
      - SPARK_WORKER_CORES=4
    ports:
      - '8081:8081'
    volumes:
      - $PWD:/home/jovyan/work
  jupyter:
    image: jupyter/pyspark-notebook:spark-3.3.1
    ports:
      - '8888:8888'
    volumes:
      - $PWD:/home/jovyan/work
